server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        add_header Cache-Control "no-store, must-revalidate";
        expires -1;
        try_files $uri $uri/ =404;
    }
}
